name: Code Climate Test Reporter Base
description: Installs and runs the CodeClimate Test Reporter tool

branding:
  icon: activity
  color: red

inputs:
  command:
    description: The commands given to the test reporter
    required: true
  version:
    description: The version of the tool to use (defaults to the latest version)
    required: false

runs:
  using: node12
  pre: pre.js
  main: main.js